# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: OnlineShop\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

 online_shop.service.promotions_service:
        class: OnlineShop\Service\PromotionsService
        autowire: true